import Qtech from "../../assets/img/qtech.png";
export let AllCasinoProviderName = {
  // "Indian Casino": [
    // {
    //   name: "Super nowa",
    //   logo: "https://supernovagamesstudios.com/wp-content/uploads/2021/06/suxnova.png",
    //   gameCode: "SP-NOWA",
    //   PageUrl: "/SuperNowa_casion",
    // },
    // {
    //   name: "Aura",
    //   logo: "https://auragaming.org/images/supercleanaura%20white.png?crc=7159781",
    //   gameCode: "AURA",
    //   PageUrl: "/casino-list",
    // },
  // ],
  "Internation Casino": [
    {
      name: "EVOLUTION",
      logo: "https://wver.sprintstaticdata.com/v14/static/front/img/icons/5.png",
      gameCode: "EVO-dhp",
      gameCodeName: "EVO",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "VIVO GAMING",
      logo: "https://wver.sprintstaticdata.com/v14/static/front/img/icons/21.png",
      gameCode: "VGL-bulgariaroulette",
      gameCodeName: "VGL",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "EZUGI",
      logo: "https://wver.sprintstaticdata.com/v14/static/front/img/icons/1.png",
      gameCode: "EZU-32cards",
      gameCodeName: "EZU",
      PageUrl: "/m/All-Games-page",
    },
    // {
    //   name: "BGAMING",
    //   logo: "https://global-uploads.webflow.com/63b2c230b49fa188ad86ffec/63f4c9689497e0d7c32f4a31_BGaming_logo.svg",
    //   gameCode: "Qtech",
    //   gameCode: "BGM",
    // },
    {
      name: "SKY WIND",
      logo: "https://skywindgroup.com/assets/site/images/skywind_white.svg",
      gameCode: "SWL-atomroulette",
      gameCodeName: "SWL",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "SA GAMING",
      logo: "https://www.sagaming.com/img/logo.png",
      gameCode: "SAG-lobby",
      gameCodeName: "SAG",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "PRAGMATIC PLAY",
      logo: "https://www.pragmaticplay.com/wp-content/themes/gp-theme-basic/libs/dist/images/PP-white-logo.svg",
      gameCode: "PPL-livecasinolobby",
      gameCodeName: "PPL",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "BETTER LIVE",
      logo: "https://live.beter.co/wp-content/themes/artit/assets/images/logo.svg",
      gameCode: "BTL-lobby",
      gameCodeName: "BTL",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "BET GAMES",
      logo: "https://www.betgames.tv/api/uploads/BG_Logo_White_Horizontal_Lock_Up_dcca475d41.png",
      gameCode: "BTV-lobby",
      gameCodeName: "BTV",
      PageUrl: "/m/All-Games-page",
    },
    // {
    //   name: " EBET",
    //   logo: "https://ebet.gg/wp-content/uploads/2022/05/EBET-logo.png",
    //   gameCode: "EBT-sicbo",
    //   gameCode: "EBT",
    // },
    {
      name: "AVIATOR",
      logo: "https://sitethemedata.com/casino_icons/fantasy/aviator.png",
      gameCode: "SPB-aviator",
      gameCodeName: "SPB",
      PageUrl: "/m/All-Games-page",
    },
    {
      name: "Q Tech",
      logo: Qtech,
      gameCode: "Qtech",
      gameCodeName: "SPB",
      PageUrl: "/m/All-Games-page",
    },
  ],
  "Fantasy Games": [
    {
      name: "Aviator",
      logo: "https://sitethemedata.com/casino_icons/fantasy/aviator.png",
      gameCode: "SPB",
      PageUrl: "casino/FantasyGame",
    },
    {
      name: "Relex",
      logo: "https://cf-cdn.relax-gaming.com/static/img/logo.svg",
      gameCode: "RLX",
      PageUrl: "casino/FantasyGame",
    },
    {
      name: "Thunder Kick",
      logo: "https://www.thunderkick.com/wp-content/uploads/2021/04/thunderkick-logo-horizontal-white.svg",
      gameCode: "TK",
      PageUrl: "casino/FantasyGame",
    },
    {
      name: "Nolimit City",
      logo: "https://www.nolimitcity.com/img/site-img/nolimit-city.png",
      gameCode: "NLC",
      PageUrl: "casino/FantasyGame",
    },
  ],
  "Slot Games": [
    {
      name: "YUILD",
      logo: "https://wver.sprintstaticdata.com/v14/static/front/img/icons/1.png",
      gameCode: "YGG",
      PageUrl: "casino/Slot",
    },
    {
      name: "1X2 GAMING",
      logo: "https://www.1x2gaming.com/img/logo@2x.png",
      gameCode: "1x2",
      PageUrl: "casino/Slot",
    },
    {
      name: "AVATAR UX",
      logo: "https://avatarux.com/wp-content/uploads/2021/06/AUX-logo.svg",
      gameCode: "AUX",
      PageUrl: "casino/Slot",
    },
    {
      name: "BIG TIME",
      logo: "https://images.squarespace-cdn.com/content/v1/60aedd95a74c4c4033f9d064/1623895434956-BV0PANOPBDWZ2FMFV53V/BTG_Logo_White.png?format=1500w",
      gameCode: "BTG",
      PageUrl: "casino/Slot",
    },
    {
      name: "BLUE PRINT",
      logo: "https://blueprintgaming.com/wp-content/uploads/2017/07/web-logo.png",
      gameCode: "BPG",
      PageUrl: "casino/Slot",
    },
    {
      name: "BOOONGO",
      logo: "https://bng.games/static/img/logo_full.svg",
      gameCode: "BNG",
      PageUrl: "casino/Slot",
    },
    {
      name: "CQ9",
      logo: "https://www.cq9gaming.com/eng/html/img/layout/LOGO.png",
      gameCode: "CQC",
      PageUrl: "casino/Slot",
    },
    {
      name: "DRAGOON SOFT",
      logo: "https://www.dragoonsoft.com/img/ds_header_logo.31834161.png",
      gameCode: "DS",
      PageUrl: "casino/Slot",
    },
    {
      name: "ELK GAMING",
      logo: "https://www.elk-studios.com/app/themes/elkstudios/assets/img/logo-new.svg",
      gameCode: "ELK",
      PageUrl: "casino/Slot",
    },
    {
      name: "EVOPLAY",
      logo: "https://evoplay.games/wp-content/themes/evoplay/assets/img/logo.svg",
      gameCode: "EVP",
      PageUrl: "casino/Slot",
    },
    {
      name: "FANTASMA",
      logo: "https://www.fantasmagames.com/wp-content/uploads/2020/05/Fantasma_logo_Vector.png",
      gameCode: "FNG",
      PageUrl: "casino/Slot",
    },
    {
      name: "FUGASO",
      logo: "https://fugaso.com/images/logo.svg",
      gameCode: "FUG",
      PageUrl: "casino/Slot",
    },
    {
      name: "GAMEART",
      logo: "https://gameart.net/wp-content/uploads/2022/12/prikazna_YS_web.jpg",
      gameCode: "GA",
      PageUrl: "casino/Slot",
    },
    {
      name: "GAME FISH",
      logo: "https://nuxgame.com/img/logo_Nuxgame_2023.webp",
      gameCode: "GFG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.yggdrasilgaming.com/w/files/2022/02/logo-header.svg",
      name: "YGGDRASIL",
      gameCode: "YGG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.woohoogames.com/themes/woohoo/images/logo.svg",
      name: "WOOHOO",
      gameCode: "WOO",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.triple-pg.com/wp-content/uploads/2023/05/logo-wh.svg",
      name: "TRIPLE",
      gameCode: "TPG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.thunderkick.com/wp-content/uploads/2021/04/thunderkick-logo-horizontal-white.svg",
      name: "THUNDER",
      gameCode: "TPG",
      PageUrl: "casino/Slot",
    },
    // {
    //   logo: "https://www.thunderkick.com/wp-content/uploads/2021/04/thunderkick-logo-horizontal-white.svg",
    //   name: "Splitrock Gaming",
    //   gameCode: "TPG",
    // PageUrl: "casino/Slot"
    // },
    // {
    //   logo: "https://wazdan.com/wp-content/themes/wazdan/assets/images/logo.svg",
    //   name: "WAZDAN",
    //   gameCode: "WAZ",
    // PageUrl: "casino/Slot"
    // },
    {
      logo: "https://www.gamblerspick.com/uploads/set_resources_3/84c1e40ea0e759e3f1505eb1788ddf3c_logo.png",
      name: "SPLITROCK",
      gameCode: "SPR",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://spearheadstudios.com/wp-content/themes/spearheadstudios/assets/img/logo.svg?v=1",
      name: "SPEAR HEAD",
      gameCode: "SHS",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://slotmill.com/wp-content/themes/slotmill-v2/assets/img/slotmill-logo-header.svg",
      name: "SLOT MILL",
      gameCode: "SM",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.skywindgroup.com/assets/site/images/skywind_white.svg",
      name: "SKYWIND",
      gameCode: "SWC",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://revolvergaming.com/wp-content/themes/RevolverGames/images/logo-middle.png",
      name: "REVOLVER",
      gameCode: "RG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.reloadedgaming.com/rel-230217/images/logo2.png",
      name: "RELOADED",
      gameCode: "RLG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://cf-cdn.relax-gaming.com/static/img/logo.svg",
      name: "RELAX",
      gameCode: "RLX",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://uploads-ssl.webflow.com/5ad9ea8824e99a21e272dacd/5ae73184a9e2a25942fb74a1_Tiger.svg",
      name: "RED TIGER",
      gameCode: "RED",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://rtgslots.com/wp-content/uploads/2020/09/RTG-SLOTS-logo.png",
      name: "RTG SLOT",
      gameCode: "RTG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://quickspin.com/wp-content/themes/quickspin/img/quickspin-logo.svg",
      name: "QUICK SPIN",
      gameCode: "QS",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.pushgaming.com/i/logo-v2-light.png",
      name: "PUSH",
      gameCode: "PUG",
      PageUrl: "casino/Slot",
    },
    {
      logo: "https://www.pragmaticplay.com/wp-content/themes/gp-theme-basic/libs/dist/images/PP-white-logo.svg",
      name: "PRAGMATIC",
      gameCode: "PPC",
      PageUrl: "casino/Slot",
    },
  ],
  Lottery: [
    {
      name: "BET GAMES",
      logo: "https://www.betgames.tv/api/uploads/BG_Logo_White_Horizontal_Lock_Up_dcca475d41.png",
      gameCode: "BTV",
      PageUrl: "casino/Lottery",
    },
    {
      name: "EVOLUTION",
      logo: "https://wver.sprintstaticdata.com/v14/static/front/img/icons/5.png",
      gameCode: "EVO",
      PageUrl: "casino/Lottery",
    },
    {
      name: "EVOPLAY",
      logo: "https://evoplay.games/wp-content/themes/evoplay/assets/img/logo.svg",
      gameCode: "EVP",
      PageUrl: "casino/Lottery",
    },
    {
      name: "GALAXSYS",
      logo: "https://galaxsys.co/wp-content/uploads/2022/02/Galaxsys.svg",
      gameCode: "GLX",
      PageUrl: "casino/Lottery",
    },
    {
      name: "PLAY GO",
      logo: "https://static.wixstatic.com/media/dad1c6_ef8a09e283c54aa9863a02228afb9852~mv2.png/v1/fill/w_272,h_74,al_c,q_95,enc_auto/playngo_logo_on_black.png",
      gameCode: "PNG",
      PageUrl: "casino/Lottery",
    },
    {
      name: "S4",
      logo: "https://media.licdn.com/dms/image/C4E0BAQGMnMvRWUcOsA/company-logo_200_200/0/1519900555706?e=1703116800&v=beta&t=ezkTp_NYg2wcB5L2JADuOxm2SyH77pKxl6aYnJ0Vuzs",
      gameCode: "S4G",
      PageUrl: "casino/Lottery",
    },
    {
      name: "SPEARHEAD",
      logo: "https://spearheadstudios.com/wp-content/themes/spearheadstudios/assets/img/logo.svg?v=1",
      gameCode: "SHS",
      PageUrl: "casino/Lottery",
    },
    {
      name: "SPRIBE",
      logo: "https://spribe.co/spribe-logo.b13289b5f5fab437.svg",
      gameCode: "SPB",
      PageUrl: "casino/Lottery",
    },
    {
      name: "TRIPLE",
      logo: "https://www.triple-pg.com/wp-content/uploads/2023/05/logo-wh.svg",
      gameCode: "TPG",
      PageUrl: "casino/Lottery",
    },
    {
      name: "KIRON",
      logo: "https://kironinteractive.com/wp-content/uploads/2022/03/Kiron-Logo-Flat-white.png",
      gameCode: "KIR",
      PageUrl: "casino/Lottery",
    },
    {
      name: "TURBO",
      logo: "https://turbogames.io/images/home/home-logo.png",
      gameCode: "TRB",
      PageUrl: "casino/Lottery",
    },
    // {
    //   logo: "https://wazdan.com/wp-content/themes/wazdan/assets/images/logo.svg",
    //   name: "WAZDAN",
    //   gameCode: "WAZ",
    // },
  ],
};
